### ISSUE TITLE
WProofreader doesn't start automatically in classic editor inside default Gutenberg editor

### ISSUE THREAD

**Issue by jshaptala** [WebSpellChecker/wproofreader-plugin-wordpress#18]
Users need to click manually in the classic editor field to launch WProofreader as it doesn't start by default in it after the page/blog is in the editable mode.

UPD. We investigated the issue and will be listening to the event form the classic (TinyMCE editor) and if it's loaded, we will initialize WProofreader there.

**Comment by lex127** [comment]
Done.
